[tool.poetry]
authors = ["None"]
description = ""
name = "src"
version = "0.1.0"

[tool.poetry.dependencies]
core = {path = "../../../modules/core"}
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
